[server]
serverNames = { "localhost", "2B5.local" } 
port = { 8080, 8090 }
root = "/nfs/adjoly/workspace/kanel.ovh"
maxPostSize = "10M"
cookies = true
uploads = false
dirlist = true
methods = {"GET", "POST", "DELETE"}
index = "index.html"

[server.errorPage]
404 = 
401 = "unauthorized.html"
402 = "uwu.html"

[server.cgi]
py = "/usr/bin/python3"
